apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  selector:
    matchLabels:
      app: splitdim
  template:
    metadata:
      labels:
        app: splitdim
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: splitdim
        image: localhost/splitdim:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
        env:
        - name: KVSTORE_MODE
          valueFrom:
            configMapKeyRef:
              name: splitdim-config
              key: kvstoreMode
        - name: KVSTORE_ADDR
          valueFrom:
            configMapKeyRef:
              name: splitdim-config
              key: kvstoreAddr
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: splitdim
  labels:
    app: splitdim
spec:
  selector:
    app: splitdim
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080